### ISSUE TITLE
Bug: Mark Many... excludes last byte.

### ISSUE THREAD

**Issue by OxyMauron** [Dotsarecool/DiztinGUIsh#38]
Marking C43842-C43843 will only mark C43842 with the indicated label.

**Comment by binary1230** [comment]
documenting my own actions.....

I did this:
![image](https://user-images.githubusercontent.com/5413064/111055956-16818c80-8449-11eb-8853-f88de0ebdff1.png)

And got this:
![image](https://user-images.githubusercontent.com/5413064/111055944-ffdb3580-8448-11eb-9a30-ae28d3558976.png)

That all works correctly, but, 

Yes, it does seem a little counterintuitive from a UX standpoint that the last number you enter isn't included in the range, even if the action performed is correct.

Seems like a decent improvement would be to make the labels be "Start at Address" and "Up to AND INCLUDING address". That would look like this:

If you enter the same address (0xC43842) in both boxes, the #bytes will say 0x01 byte count
If you enter the start = 0xC43842, up to and including 0xC43843, the #bytes will say 0x02 byte count
If you enter the start = 0xC43842, up to and including 0xC43851, the #bytes will say 0x10 byte count
If you enter the start = 0xC43842, up to and including 0xC43852, the #bytes will say 0x11 byte count

If you enter 0xC43842 and 0xF bytes, then it marks 0xC00000 thru and including 0xC00010



----

I needed to mock this up just to get my head around it, so if you did:

start @ 0xC00010
up to AND INCLUDING 0xC0001F
then it would say "16 bytes" marked and look like this:

![image](https://user-images.githubusercontent.com/5413064/111056650-b5f54e00-844e-11eb-89f7-1cba96178141.png)

I think that makes a bit more sense intuitively, since users are more likely to enter the starting address and # of bytes, and have the form calculate the rest.  When it does, the second ending number will reflect something actually being marked and not "one beyond" that.

I'm going to sleep on this but good with implementing this change if no one else objects

**Comment by binary1230** [comment]
Changing it to be like this

Before:
![image](https://user-images.githubusercontent.com/5413064/119248366-aedd7100-bb5e-11eb-9fdd-64b2fa90029e.png)

after:
![image](https://user-images.githubusercontent.com/5413064/119248388-d3d1e400-bb5e-11eb-9c82-3b7c4372e556.png)

**Comment by binary1230** [comment]
fixed in master branch, next build will have this
